my_tuple = (1, 2, 3, 4)
print(my_tuple)
print(my_tuple[2])
print(my_tuple[0:3])
print(len(my_tuple))
del my_tuple
my_tuple2 = (89, 43, 90, 56, 90, 90)
print(my_tuple2)
print(max(my_tuple2))
print(min(my_tuple2))
print(sum(my_tuple2))
print(max(my_tuple2)/len(my_tuple2))
print(my_tuple2.index(43))
print(my_tuple2.count(90))
del my_tuple2
my_tuple3 = ("Serma", "Becky", "Onyore")
print(my_tuple3)
print(len(my_tuple3))
print(my_tuple3.index("Onyore"))
print(my_tuple3.count("Becky"))
